import type { Project } from "@/types/project";
import { slugify } from "@/lib/slugify";

/** Plain-text export of a saved project's full ad kit, ready to paste anywhere. */
export function buildProjectTextFile(project: Project): string {
  const { adKit } = project;
  const createdDate = new Date(project.createdAt).toLocaleString();

  const lines: string[] = [
    `PRODUCT: ${project.productName}`,
    `CATEGORY: ${project.category}`,
    `LANGUAGE: ${project.language}`,
    `CREATED: ${createdDate}`,
    `IMAGE: ${project.imageUrl}`,
    "",
    "=".repeat(60),
    "PRODUCT ANALYSIS",
    "=".repeat(60),
    adKit.analysis,
    "",
    "=".repeat(60),
    "HOOKS",
    "=".repeat(60),
    ...adKit.hooks.map((hook, i) => `${i + 1}. ${hook}`),
    "",
    "=".repeat(60),
    "15-SECOND SCRIPT",
    "=".repeat(60),
    adKit.script,
    "",
    "=".repeat(60),
    "KLING VIDEO PROMPT",
    "=".repeat(60),
    adKit.klingPrompt,
    "",
    "=".repeat(60),
    "WHATSAPP MESSAGE",
    "=".repeat(60),
    adKit.whatsappMessage,
    "",
    "=".repeat(60),
    "INSTAGRAM CAPTION",
    "=".repeat(60),
    adKit.instagramCaption,
    "",
    "=".repeat(60),
    "HASHTAGS",
    "=".repeat(60),
    adKit.hashtags.map((tag) => (tag.startsWith("#") ? tag : `#${tag}`)).join(" "),
    "",
    "Generated by Offer For You - BNK AI Ad Studio",
  ];

  return lines.join("\n");
}

/** Triggers a real client-side file download of the project's ad kit as .txt. */
export function downloadProjectAsText(project: Project): void {
  const content = buildProjectTextFile(project);
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = `${slugify(project.productName)}-ad-kit.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}
